/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thirdpartyninjas_test_TestJni */

#ifndef _Included_com_thirdpartyninjas_test_TestJni
#define _Included_com_thirdpartyninjas_test_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thirdpartyninjas_test_TestJni
 * Method:    init
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_test_TestJni_init
  (JNIEnv *, jobject, jint, jint, jstring);

/*
 * Class:     com_thirdpartyninjas_test_TestJni
 * Method:    update
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_test_TestJni_update
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_thirdpartyninjas_test_TestJni
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_test_TestJni_draw
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
