/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thirdpartyninjas_NinjaPartyTest_NinjaJni */

#ifndef _Included_com_thirdpartyninjas_NinjaPartyTest_NinjaJni
#define _Included_com_thirdpartyninjas_NinjaPartyTest_NinjaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thirdpartyninjas_NinjaPartyTest_NinjaJni
 * Method:    init
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_NinjaPartyTest_NinjaJni_init
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_thirdpartyninjas_NinjaPartyTest_NinjaJni
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_NinjaPartyTest_NinjaJni_destroy
  (JNIEnv *, jclass);

/*
 * Class:     com_thirdpartyninjas_NinjaPartyTest_NinjaJni
 * Method:    setResolution
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_NinjaPartyTest_NinjaJni_setResolution
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_thirdpartyninjas_NinjaPartyTest_NinjaJni
 * Method:    update
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_NinjaPartyTest_NinjaJni_update
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_thirdpartyninjas_NinjaPartyTest_NinjaJni
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_NinjaPartyTest_NinjaJni_draw
  (JNIEnv *, jclass);

/*
 * Class:     com_thirdpartyninjas_NinjaPartyTest_NinjaJni
 * Method:    pause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_NinjaPartyTest_NinjaJni_pause
  (JNIEnv *, jclass);

/*
 * Class:     com_thirdpartyninjas_NinjaPartyTest_NinjaJni
 * Method:    resume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_NinjaPartyTest_NinjaJni_resume
  (JNIEnv *, jclass);

/*
 * Class:     com_thirdpartyninjas_NinjaPartyTest_NinjaJni
 * Method:    touchDown
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_NinjaPartyTest_NinjaJni_touchDown
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_thirdpartyninjas_NinjaPartyTest_NinjaJni
 * Method:    touchUp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_NinjaPartyTest_NinjaJni_touchUp
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_thirdpartyninjas_NinjaPartyTest_NinjaJni
 * Method:    touchMove
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_NinjaPartyTest_NinjaJni_touchMove
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_thirdpartyninjas_NinjaPartyTest_NinjaJni
 * Method:    touchCancel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_NinjaPartyTest_NinjaJni_touchCancel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
