/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thirdpartyninjas_test_TestJni */

#ifndef _Included_com_thirdpartyninjas_test_TestJni
#define _Included_com_thirdpartyninjas_test_TestJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thirdpartyninjas_test_TestJni
 * Method:    init
 * Signature: (IILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_test_TestJni_init
  (JNIEnv *, jclass, jint, jint, jstring);

/*
 * Class:     com_thirdpartyninjas_test_TestJni
 * Method:    update
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_test_TestJni_update
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     com_thirdpartyninjas_test_TestJni
 * Method:    draw
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_test_TestJni_draw
  (JNIEnv *, jclass);

/*
 * Class:     com_thirdpartyninjas_test_TestJni
 * Method:    touchDown
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_test_TestJni_touchDown
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_thirdpartyninjas_test_TestJni
 * Method:    touchUp
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_test_TestJni_touchUp
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_thirdpartyninjas_test_TestJni
 * Method:    touchMove
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_test_TestJni_touchMove
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_thirdpartyninjas_test_TestJni
 * Method:    touchCancel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_thirdpartyninjas_test_TestJni_touchCancel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
